1.1.0 release
coingate/shopware-plugin pull request #7
Opened 2022-09-23 23:08 UTC by linaspasv

Various compatibility fixes. Minimal Shopware support is 5.3.0

2022-09-26 14:29 UTC, vgumonis requested changes

2022-09-26 14:29 UTC, vgumonis commented on custom/plugins/CoinGatePayment/Controllers/Frontend/CoinGatePayment.php
> +        if ($order->status == 'paid') {
why is only paid handled ? the user could close the invoice in the browser and if the callback is not handled the order will per indefinitely pending 

perhaps we should also include a payment method check, so not to change statuses or orders that had their payment method changed

2022-09-26 16:15 UTC, linaspasv commented on custom/plugins/CoinGatePayment/Controllers/Frontend/CoinGatePayment.php
> +        if ($order->status == 'paid') {
SW5 does not create actual order until ``saveOrder`` method is called, and we call it only after receiving confirmation about payment. There is a temporary order where bucket and user data is stored but it's not viewable on the backend anywhere (think about it as a session, that we can access through token passed back by CoinGate on a webhook call).

SW5 is really tricky when it comes to an async payment methods, e.g. original plugin executed ``saveOrder`` only if user clicked on "back to merchant" and this was the main reason it did not work. :-)

2022-09-27 09:23 UTC, vgumonis approved these changes

2022-09-27 09:23 UTC, merged